//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPcrmProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDistribution
    {
        public string CustomerId { get; set; }
        public string distributionId { get; set; }
    }
}
