//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPcrmProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Name { get; set; }
        public System.DateTime FinalDate { get; set; }
        public string Description { get; set; }
        public string Department { get; set; }
        public Nullable<bool> Done { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
